[template]
src = "haproxy.tmpl"
dest  = "/usr/local/etc/haproxy/haproxy.cfg"
keys  = [
    "ENDPOINTS", "HAPROXY_K8S_API_PORT", "HAPROXY_STATE_PORT"
]

check_cmd = "haproxy -c -f {{ .src }}"
reload_cmd  = "haproxy -f /usr/local/etc/haproxy/haproxy.cfg -p /run/haproxy.pid -D -sf $(cat /run/haproxy.pid) -x /run/haproxy.sock"
