[template]
src = "keepalived.tmpl"
dest  = "/usr/local/etc/keepalived/keepalived.conf"
keys  = [
    "ENDPOINTS", "KEEPALIVED_HAPROXY_VIP", "KEEPALIVED_INTERFACE", "KEEPALIVED_PRIORITY", "KEEPALIVED_VIRTUAL_ROUTER_ID", "KEEPALIVED_AUTH_PASS"
]

reload_cmd  = "kill -HUP $(cat /run/keepalived.pid)"

